# This workflow will run to update the installer library of
# Docker images.  These are the images which provide updated wheels
# .deb installation packages or maybe just some compiled library

name: Build Installer Library

on:
  workflow_dispatch:
    inputs:
      psycopg2_version:
        description: 'psycopg2 version'
        type: string
        required: true
        default: '2.9.7'
      jbig2enc_version:
        description: 'jbig2enc version'
        type: string
        required: true
        default: '0.30'

concurrency:
  group: build-installer-library
  cancel-in-progress: false

jobs:

  build-jbig2enc:
    name: jbig2enc @ ${{ inputs.jbig2enc_version }}
    uses: ./.github/workflows/reusable-builder.yml
    secrets: inherit
    with:
      name: jbig2enc
      version: ${{ inputs.jbig2enc_version }}
      dockerfile: ./jbig2enc.dockerfile
      build-args: |
        JBIG2ENC_VERSION=${{ inputs.jbig2enc_version }}

  build-psycopg2-wheel:
    name: psycopg2 @ ${{ inputs.psycopg2_version }}
    uses: ./.github/workflows/reusable-builder.yml
    secrets: inherit
    with:
      name: psycopg2
      version: ${{ inputs.psycopg2_version }}
      dockerfile: ./psycopg2.dockerfile
      build-args: |
        PSYCOPG2_VERSION=${{ inputs.psycopg2_version }}

  commit-binary-files:
    name: Store installers
    needs:
      - build-jbig2enc
      - build-psycopg2-wheel
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: binary-library
      -
        name: Clear old installers
        run: |
          rm --verbose --recursive --force jbig2enc
          rm --verbose --recursive --force psycopg2
      -
        name: Download psycopg2 files
        uses: actions/download-artifact@v4
        with:
          name: psycopg2-${{ inputs.psycopg2_version }}
          path: ./psycopg2
      -
        name: Download jbig2enc files
        uses: actions/download-artifact@v4
        with:
          name: jbig2enc-${{ inputs.jbig2enc_version }}
          path: ./jbig2enc
      -
        name: Show file structure
        run: |
          tree .
      -
        name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add psycopg2/ jbig2enc/
          git status
          git commit -m "Updating installer packages" || true
          git push origin || true
